import { Opcode } from './Opcode'
import { opSTOP } from './control'
import {
  opADD,
  opMUL,
  opSUB,
  opDIV,
  opSDIV,
  opMOD,
  opSMOD,
  opADDMOD,
  opMULMOD,
  opEXP,
  opSIGNEXTEND,
  opLT,
  opGT,
  opSLT,
  opSGT,
  opEQ,
  opISZERO,
  opAND,
  opOR,
  opXOR,
  opNOT,
  opBYTE,
  opSHL,
  opSHR,
  opSAR,
} from './machineWord'
import { invalidOpcode } from './invalid'
import { opDup, opSwap, opPop } from './stack'

export { opUnreachable } from './invalid'
export { opPush } from './stack'

export function getOpcode (hex: string) {
  return OP_CODES[hex] ?? invalidOpcode(hex)
}

/* eslint-disable quote-props */
const OP_CODES: Record<string, Opcode | undefined> = {
  '00': opSTOP,
  '01': opADD,
  '02': opMUL,
  '03': opSUB,
  '04': opDIV,
  '05': opSDIV,
  '06': opMOD,
  '07': opSMOD,
  '08': opADDMOD,
  '09': opMULMOD,
  '0a': opEXP,
  '0b': opSIGNEXTEND,
  '10': opLT,
  '11': opGT,
  '12': opSLT,
  '13': opSGT,
  '14': opEQ,
  '15': opISZERO,
  '16': opAND,
  '17': opOR,
  '18': opXOR,
  '19': opNOT,
  '1a': opBYTE,
  '1b': opSHL,
  '1c': opSHR,
  '1d': opSAR,
  '50': opPop,
  // 60 - 7f PUSH - handled differently
  '80': opDup(1),
  '81': opDup(2),
  '82': opDup(3),
  '83': opDup(4),
  '84': opDup(5),
  '85': opDup(6),
  '86': opDup(7),
  '87': opDup(8),
  '88': opDup(9),
  '89': opDup(10),
  '8a': opDup(11),
  '8b': opDup(12),
  '8c': opDup(13),
  '8d': opDup(14),
  '8e': opDup(15),
  '8f': opDup(16),
  '90': opSwap(1),
  '91': opSwap(2),
  '92': opSwap(3),
  '93': opSwap(4),
  '94': opSwap(5),
  '95': opSwap(6),
  '96': opSwap(7),
  '97': opSwap(8),
  '98': opSwap(9),
  '99': opSwap(10),
  '9a': opSwap(11),
  '9b': opSwap(12),
  '9c': opSwap(13),
  '9d': opSwap(14),
  '9e': opSwap(15),
  '9f': opSwap(16),
}
